name: AWS Service CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
  NODE_VERSION: '20.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install CDK
        run: |
          npm install -g aws-cdk
          npm install -g aws-cdk-local
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-east-1"
      - name: Unit tests
        run: echo "Execute some unit tests here"

      - name: CDK Synth 
        #run: npm run cdk -w cdk -- synth -q
        run: cdklocal synth
        
      - name: CDK Deploy to AWS
        run: cdklocal deploy --require-approval=never
        #run: npm run cdk -w cdk -- deploy --require-approval never

      - name: E2E tests
        run: echo "Execute some End-to-End tests here"
